### ISSUE TITLE
Bug: get_user missing

### ISSUE THREAD

**Issue by themire** [kinde-oss/kinde-ruby-sdk#54]
### Prerequisites

- [x] I have searched the repository’s issues and [Kinde community](https://thekindecommunity.slack.com/archives/C04K316BXEH) to ensure my issue isn’t a duplicate
- [x] I have checked the latest version of the library to replicate my issue
- [x] I have read the [contributing guidelines](https://github.com/kinde-oss/.github/blob/main/.github/CONTRIBUTING.md)
- [x] I agree to the terms within the [code of conduct](https://github.com/kinde-oss/.github/blob/main/.github/CODE_OF_CONDUCT.md)

### Describe the issue

I'm getting this in production after upgrading to 1.6.5. Did the gem have breaking changes?

```
undefined method 'get_user' for #<KindeApi::OAuthApi:0x00003ed837be5cf0> (NoMethodError)

    user_hash = KindeSdk.client(tokens).oauth.get_user
                                             ^^^^^^^^^
```

### Library URL

https://github.com/kinde-oss/kinde-ruby-sdk

### Library version

1.6.5

### Operating system(s)

Other (see “Further environment details”)

### Operating system version(s)

N/A

**Comment by brettchaldecott** [comment]
@themire we have released 1.6.6. This contains backwards compatibility for the get_user function. Please review and let us know.

**Comment by themire** [comment]
The docs still suggest to use get_user btw 

https://docs.kinde.com/developer-tools/sdks/backend/ruby-sdk/
